version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: anpr_mysql_v8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: anpr_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  anpr_app:
    build: .
    container_name: anpr_master_app
    restart: always
    depends_on:
      - mysql_db
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=mysql_db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=anpr_db
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./storage:/app/storage

volumes:
  mysql_data:
